[clean]
# The output dir for all final assets.
dist = "dist"
# Optionally perform a cargo clean.
cargo = false

[serve]
# The address to serve on.
address = "127.0.0.1"
# The port to serve on.
port = 3030
# Open a browser tab once the initial build is complete.
open = false
# Disable auto-reload of the web app.
no_autoreload = true

